# Generated by Django 5.0.4 on 2024-07-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registroproduccion_fecha_produccion'),
        ('core', '0003_registroauditoriaactualizacion'),
    ]

    operations = [
    ]
